/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kaimone;

import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author nano
 */
public class AccSettings extends javax.swing.JFrame {

    /**
     * Creates new form AccSettings
     */
    public AccSettings() {
        super("Kaimono | Bye Groceries Online!");
            String name = "";
            String email = "";
            String password = "";
            try{
                conn con = new conn();
                String sql = "SELECT * FROM cur_user";
                Statement s = con.c.createStatement();
                ResultSet rs = s.executeQuery(sql);
                rs.next();
                name = rs.getString("username");
                email = rs.getString("email");
                password = rs.getString("password");
            }
            catch(Exception e){
                e.getStackTrace();
            }
            initComponents();
            this.username.setText(name);
            this.UsernameField.setText(name);
            this.EmailField.setText(email);
            this.Password.setText(password);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        Nav = new javax.swing.JPanel();
        KaimonoH = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Logout = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        MyCart = new javax.swing.JPanel();
        cartlable = new javax.swing.JLabel();
        Checkout = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Settings = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Feedbacks = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        SaveChanges = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Back = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        Heading = new javax.swing.JLabel();
        seprator = new javax.swing.JSeparator();
        edit2 = new javax.swing.JLabel();
        edit1 = new javax.swing.JLabel();
        edit3 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        showpass = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(153, 153, 255));
        MainPanel.setForeground(new java.awt.Color(255, 255, 255));

        Nav.setBackground(new java.awt.Color(51, 0, 204));

        KaimonoH.setBackground(new java.awt.Color(153, 153, 255));
        KaimonoH.setFont(new java.awt.Font("Baloo Da 2", 0, 24)); // NOI18N
        KaimonoH.setForeground(new java.awt.Color(255, 255, 255));
        KaimonoH.setText("Kaimono");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        Logout.setFont(new java.awt.Font("Baloo Da 2", 0, 14)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("Logout");
        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });

        username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username.setText("Username");

        MyCart.setBackground(new java.awt.Color(51, 0, 204));
        MyCart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        MyCart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MyCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyCartMouseClicked(evt);
            }
        });

        cartlable.setForeground(new java.awt.Color(255, 255, 255));
        cartlable.setText("My Cart");

        javax.swing.GroupLayout MyCartLayout = new javax.swing.GroupLayout(MyCart);
        MyCart.setLayout(MyCartLayout);
        MyCartLayout.setHorizontalGroup(
            MyCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyCartLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(cartlable)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MyCartLayout.setVerticalGroup(
            MyCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyCartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cartlable, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        Checkout.setBackground(new java.awt.Color(51, 0, 204));
        Checkout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Checkout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Checkout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckoutMouseClicked(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Checkout");

        javax.swing.GroupLayout CheckoutLayout = new javax.swing.GroupLayout(Checkout);
        Checkout.setLayout(CheckoutLayout);
        CheckoutLayout.setHorizontalGroup(
            CheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckoutLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CheckoutLayout.setVerticalGroup(
            CheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        Settings.setBackground(new java.awt.Color(51, 0, 204));
        Settings.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Settings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SettingsMouseClicked(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Settings");

        javax.swing.GroupLayout SettingsLayout = new javax.swing.GroupLayout(Settings);
        Settings.setLayout(SettingsLayout);
        SettingsLayout.setHorizontalGroup(
            SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingsLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SettingsLayout.setVerticalGroup(
            SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        Feedbacks.setBackground(new java.awt.Color(51, 0, 204));
        Feedbacks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Feedbacks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Feedbacks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FeedbacksMouseClicked(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Feedbacks");

        javax.swing.GroupLayout FeedbacksLayout = new javax.swing.GroupLayout(Feedbacks);
        Feedbacks.setLayout(FeedbacksLayout);
        FeedbacksLayout.setHorizontalGroup(
            FeedbacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FeedbacksLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FeedbacksLayout.setVerticalGroup(
            FeedbacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FeedbacksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout NavLayout = new javax.swing.GroupLayout(Nav);
        Nav.setLayout(NavLayout);
        NavLayout.setHorizontalGroup(
            NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Feedbacks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NavLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KaimonoH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NavLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(Logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(34, 34, 34))
                    .addComponent(MyCart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Checkout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Settings, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NavLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27)))
                .addGap(24, 24, 24))
        );
        NavLayout.setVerticalGroup(
            NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(KaimonoH, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(username)
                .addGap(18, 18, 18)
                .addComponent(MyCart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Checkout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Settings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Feedbacks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Logout)
                .addGap(17, 17, 17))
        );

        SaveChanges.setBackground(new java.awt.Color(51, 0, 204));
        SaveChanges.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SaveChanges.setEnabled(false);
        SaveChanges.setFont(new java.awt.Font("Baloo Da 2", 0, 12)); // NOI18N
        SaveChanges.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveChangesMouseClicked(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("SAVE CHANGES");

        javax.swing.GroupLayout SaveChangesLayout = new javax.swing.GroupLayout(SaveChanges);
        SaveChanges.setLayout(SaveChangesLayout);
        SaveChangesLayout.setHorizontalGroup(
            SaveChangesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SaveChangesLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(46, 46, 46))
        );
        SaveChangesLayout.setVerticalGroup(
            SaveChangesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SaveChangesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        Back.setBackground(new java.awt.Color(51, 0, 204));
        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.setFont(new java.awt.Font("Baloo Da 2", 0, 12)); // NOI18N
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("BACK");

        javax.swing.GroupLayout BackLayout = new javax.swing.GroupLayout(Back);
        Back.setLayout(BackLayout);
        BackLayout.setHorizontalGroup(
            BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel11)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        BackLayout.setVerticalGroup(
            BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        UsernameField.setEditable(false);
        UsernameField.setBackground(new java.awt.Color(153, 153, 255));
        UsernameField.setForeground(new java.awt.Color(255, 255, 255));
        UsernameField.setText("Username");

        EmailField.setEditable(false);
        EmailField.setBackground(new java.awt.Color(153, 153, 255));
        EmailField.setForeground(new java.awt.Color(255, 255, 255));
        EmailField.setText("Email");

        Heading.setFont(new java.awt.Font("Baloo Da 2", 0, 36)); // NOI18N
        Heading.setForeground(new java.awt.Color(255, 255, 255));
        Heading.setText("Account Settings");

        seprator.setBackground(new java.awt.Color(255, 255, 255));
        seprator.setForeground(new java.awt.Color(255, 255, 255));

        edit2.setIcon(new javax.swing.ImageIcon("C:\\Users\\nano\\Documents\\NetBeansProjects\\Kaimono\\src\\main\\java\\kaimone\\edit.png")); // NOI18N
        edit2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit2MouseClicked(evt);
            }
        });

        edit1.setIcon(new javax.swing.ImageIcon("C:\\Users\\nano\\Documents\\NetBeansProjects\\Kaimono\\src\\main\\java\\kaimone\\edit.png")); // NOI18N
        edit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit1MouseClicked(evt);
            }
        });

        edit3.setIcon(new javax.swing.ImageIcon("C:\\Users\\nano\\Documents\\NetBeansProjects\\Kaimono\\src\\main\\java\\kaimone\\edit.png")); // NOI18N
        edit3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit3MouseClicked(evt);
            }
        });

        Password.setBackground(new java.awt.Color(153, 153, 255));
        Password.setFont(new java.awt.Font("Baloo Da 2", 0, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("jPasswordField1");

        showpass.setBackground(new java.awt.Color(153, 153, 255));
        showpass.setForeground(new java.awt.Color(255, 255, 255));
        showpass.setText("Show Password");
        showpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showpassMouseClicked(evt);
            }
        });
        showpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(Nav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(SaveChanges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(EmailField, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                                    .addComponent(Password))
                                .addGap(27, 27, 27)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edit3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edit2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(showpass)))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(Heading))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(edit1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seprator, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(53, 53, 53))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Heading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addComponent(seprator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(edit1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(32, 32, 32)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit2))
                .addGap(31, 31, 31)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(edit3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Password))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showpass)
                .addGap(24, 24, 24)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveChanges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
            .addComponent(Nav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        MainMenu mm = new MainMenu();
        this.setVisible(false);
        mm.setVisible(true);
    }//GEN-LAST:event_BackMouseClicked

    private void edit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit1MouseClicked
        this.UsernameField.setEditable(true);
        this.SaveChanges.setEnabled(true);
        this.UsernameField.setText("");
    }//GEN-LAST:event_edit1MouseClicked

    private void edit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit2MouseClicked
        this.EmailField.setEditable(true);
        this.SaveChanges.setEnabled(true);
        this.EmailField.setText("");
    }//GEN-LAST:event_edit2MouseClicked

    private void edit3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit3MouseClicked
        this.Password.setEditable(true);
        this.SaveChanges.setEnabled(true);
        this.Password.setText("");
    }//GEN-LAST:event_edit3MouseClicked

    private void SaveChangesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveChangesMouseClicked
        String changed_Username = this.UsernameField.getText();
        String changed_Email = this.EmailField.getText();
        String changed_Password = this.Password.getText();
        
        if(changed_Username.isEmpty() || changed_Email.isEmpty() || changed_Password.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Fill in new Values!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
                try{
                conn con = new conn();

                //Updating account

                String sql = "update userinfo set username = ?, email = ?, password = ? where username = ?";
                PreparedStatement st = con.c.prepareStatement(sql);
                st.setString(1, changed_Username);
                st.setString(2, changed_Email);
                st.setString(3, changed_Password);
                st.setString(4, this.username.getText());


                int i = st.executeUpdate();
                if(i>0){
                    JOptionPane.showMessageDialog(null, "Your account has been updated, please login again!");
                }
                
                //Logout
                try{
                    Statement s = con.c.createStatement();
                    String query = "delete from cur_user";
                    s.executeUpdate(query);

                }catch (Exception e){
                    e.getStackTrace();
                }
                
                //New Login Page
                this.setVisible(false);
                new LoginPage().setVisible(true);
            }
            catch(Exception e){
                e.getStackTrace();
            }
        }
    }//GEN-LAST:event_SaveChangesMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked

        try{
            conn con = new conn();
            Statement s = con.c.createStatement();
            String query = "delete from cur_user";
            String query2 = "delete from user_cart";
            s.executeUpdate(query);
            s.executeUpdate(query2);

        }catch (Exception e){
            e.getStackTrace();
        }

        JOptionPane.showMessageDialog(this, "Sucessfully Logout!", "Logout", JOptionPane.PLAIN_MESSAGE);

        LoginPage l = new LoginPage();
        this.setVisible(false);
        l.setVisible(true);
    }//GEN-LAST:event_LogoutMouseClicked

    private void SettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMouseClicked

    }//GEN-LAST:event_SettingsMouseClicked

    private void FeedbacksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FeedbacksMouseClicked
        Feedback f = new Feedback();
        this.setVisible(false);
        f.setVisible(true);
    }//GEN-LAST:event_FeedbacksMouseClicked

    private void MyCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyCartMouseClicked
        MyCart mc = new MyCart();
        this.setVisible(false);
        mc.setVisible(true);
    }//GEN-LAST:event_MyCartMouseClicked

    private void CheckoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckoutMouseClicked
        Checkout c = new Checkout();
        this.setVisible(false);
        c.setVisible(true);
    }//GEN-LAST:event_CheckoutMouseClicked

    private void showpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showpassActionPerformed

    private void showpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showpassMouseClicked
        if(showpass.isSelected()){
            this.Password.setEchoChar((char)0);
        }
        else
        this.Password.setEchoChar('*');
    }//GEN-LAST:event_showpassMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccSettings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Back;
    private javax.swing.JPanel Checkout;
    private javax.swing.JTextField EmailField;
    private javax.swing.JPanel Feedbacks;
    private javax.swing.JLabel Heading;
    private javax.swing.JLabel KaimonoH;
    private javax.swing.JLabel Logout;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel MyCart;
    private javax.swing.JPanel Nav;
    private javax.swing.JPasswordField Password;
    private javax.swing.JPanel SaveChanges;
    private javax.swing.JPanel Settings;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel cartlable;
    private javax.swing.JLabel edit1;
    private javax.swing.JLabel edit2;
    private javax.swing.JLabel edit3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator seprator;
    private javax.swing.JCheckBox showpass;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
