/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kaimone;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author nano
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    
    //Used for increment
    Integer i = 1;
    Integer j = 2;
    
    public MainMenu() {
        super("Kaimono | Bye Groceries Online!");
        String name = "";
        
        try{
            conn con = new conn();
            String sql = "SELECT * FROM cur_user";
            Statement s = con.c.createStatement();
            ResultSet rs = s.executeQuery(sql);
            
            rs.next();
            name = rs.getString("username");
            
            conn con2 = new conn();
        }
        catch(Exception e){
            e.getStackTrace();
        }
        
        initComponents();
        this.username.setText(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        Nav = new javax.swing.JPanel();
        KaimonoH = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Logout = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        MyCart = new javax.swing.JPanel();
        cartlable = new javax.swing.JLabel();
        Checkout = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Settings = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Feedbacks = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Image1 = new javax.swing.JLabel();
        Image2 = new javax.swing.JLabel();
        Cont1 = new javax.swing.JPanel();
        Item1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        item1_Quantity = new javax.swing.JComboBox<>();
        Item1_Price = new javax.swing.JLabel();
        item1_Add = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Cont2 = new javax.swing.JPanel();
        Item2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        item2_Quantity = new javax.swing.JComboBox<>();
        Item2_Price = new javax.swing.JLabel();
        item2_Add = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Next = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Previous = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(153, 153, 255));

        Nav.setBackground(new java.awt.Color(51, 0, 204));

        KaimonoH.setBackground(new java.awt.Color(153, 153, 255));
        KaimonoH.setFont(new java.awt.Font("Baloo Da 2", 0, 24)); // NOI18N
        KaimonoH.setForeground(new java.awt.Color(255, 255, 255));
        KaimonoH.setText("Kaimono");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        Logout.setFont(new java.awt.Font("Baloo Da 2", 0, 14)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("Logout");
        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });

        username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username.setText("Username");

        MyCart.setBackground(new java.awt.Color(51, 0, 204));
        MyCart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        MyCart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MyCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyCartMouseClicked(evt);
            }
        });

        cartlable.setForeground(new java.awt.Color(255, 255, 255));
        cartlable.setText("My Cart");

        javax.swing.GroupLayout MyCartLayout = new javax.swing.GroupLayout(MyCart);
        MyCart.setLayout(MyCartLayout);
        MyCartLayout.setHorizontalGroup(
            MyCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyCartLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(cartlable)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MyCartLayout.setVerticalGroup(
            MyCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyCartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cartlable, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        Checkout.setBackground(new java.awt.Color(51, 0, 204));
        Checkout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Checkout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Checkout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckoutMouseClicked(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Checkout");

        javax.swing.GroupLayout CheckoutLayout = new javax.swing.GroupLayout(Checkout);
        Checkout.setLayout(CheckoutLayout);
        CheckoutLayout.setHorizontalGroup(
            CheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckoutLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CheckoutLayout.setVerticalGroup(
            CheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        Settings.setBackground(new java.awt.Color(51, 0, 204));
        Settings.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Settings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SettingsMouseClicked(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Settings");

        javax.swing.GroupLayout SettingsLayout = new javax.swing.GroupLayout(Settings);
        Settings.setLayout(SettingsLayout);
        SettingsLayout.setHorizontalGroup(
            SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingsLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SettingsLayout.setVerticalGroup(
            SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        Feedbacks.setBackground(new java.awt.Color(51, 0, 204));
        Feedbacks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Feedbacks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Feedbacks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FeedbacksMouseClicked(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Feedbacks");

        javax.swing.GroupLayout FeedbacksLayout = new javax.swing.GroupLayout(Feedbacks);
        Feedbacks.setLayout(FeedbacksLayout);
        FeedbacksLayout.setHorizontalGroup(
            FeedbacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FeedbacksLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FeedbacksLayout.setVerticalGroup(
            FeedbacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FeedbacksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout NavLayout = new javax.swing.GroupLayout(Nav);
        Nav.setLayout(NavLayout);
        NavLayout.setHorizontalGroup(
            NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Feedbacks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NavLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KaimonoH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NavLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(Logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(34, 34, 34))
                    .addComponent(MyCart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Checkout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Settings, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(username, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        NavLayout.setVerticalGroup(
            NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(KaimonoH, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(username)
                .addGap(18, 18, 18)
                .addComponent(MyCart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Checkout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Settings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Feedbacks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Logout)
                .addGap(17, 17, 17))
        );

        Image1.setIcon(new javax.swing.ImageIcon("C:\\Users\\nano\\Documents\\NetBeansProjects\\Kaimono\\src\\main\\java\\kaimone\\Vegitables\\1.jpg")); // NOI18N
        Image1.setText("jLabel1");

        Image2.setIcon(new javax.swing.ImageIcon("C:\\Users\\nano\\Documents\\NetBeansProjects\\Kaimono\\src\\main\\java\\kaimone\\Vegitables\\2.jpg")); // NOI18N
        Image2.setText("jLabel1");

        Cont1.setBackground(new java.awt.Color(51, 0, 204));
        Cont1.setPreferredSize(new java.awt.Dimension(173, 146));

        Item1.setFont(new java.awt.Font("Baloo Da 2", 0, 16)); // NOI18N
        Item1.setForeground(new java.awt.Color(255, 255, 255));
        Item1.setText("Carrot");

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        item1_Quantity.setBackground(new java.awt.Color(153, 153, 255));
        item1_Quantity.setForeground(new java.awt.Color(255, 255, 255));
        item1_Quantity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quantity", "1 Kg", "2.5 Kg", "5 Kg", "10 Kg" }));
        item1_Quantity.setBorder(null);
        item1_Quantity.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Item1_Price.setForeground(new java.awt.Color(255, 255, 255));
        Item1_Price.setText("Price: Rs.50/kg");

        item1_Add.setBackground(new java.awt.Color(153, 153, 255));
        item1_Add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        item1_Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item1_AddMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Baloo Da 2", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADD TO CART");

        javax.swing.GroupLayout item1_AddLayout = new javax.swing.GroupLayout(item1_Add);
        item1_Add.setLayout(item1_AddLayout);
        item1_AddLayout.setHorizontalGroup(
            item1_AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item1_AddLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        item1_AddLayout.setVerticalGroup(
            item1_AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item1_AddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Cont1Layout = new javax.swing.GroupLayout(Cont1);
        Cont1.setLayout(Cont1Layout);
        Cont1Layout.setHorizontalGroup(
            Cont1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cont1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Cont1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(item1_Add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Cont1Layout.createSequentialGroup()
                        .addGroup(Cont1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(item1_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Item1_Price)
                            .addComponent(Item1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(Cont1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Cont1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        Cont1Layout.setVerticalGroup(
            Cont1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Cont1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Item1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(Item1_Price)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(item1_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(item1_Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
            .addGroup(Cont1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Cont1Layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(91, Short.MAX_VALUE)))
        );

        Cont2.setBackground(new java.awt.Color(51, 0, 204));

        Item2.setFont(new java.awt.Font("Baloo Da 2", 0, 16)); // NOI18N
        Item2.setForeground(new java.awt.Color(255, 255, 255));
        Item2.setText("Cauliflower");

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        item2_Quantity.setBackground(new java.awt.Color(153, 153, 255));
        item2_Quantity.setForeground(new java.awt.Color(255, 255, 255));
        item2_Quantity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quantity", "1 Kg", "2.5 Kg", "5 Kg", "10 Kg" }));
        item2_Quantity.setBorder(null);
        item2_Quantity.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Item2_Price.setForeground(new java.awt.Color(255, 255, 255));
        Item2_Price.setText("Price: Rs.150/kg");

        item2_Add.setBackground(new java.awt.Color(153, 153, 255));
        item2_Add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        item2_Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item2_AddMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Baloo Da 2", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ADD TO CART");

        javax.swing.GroupLayout item2_AddLayout = new javax.swing.GroupLayout(item2_Add);
        item2_Add.setLayout(item2_AddLayout);
        item2_AddLayout.setHorizontalGroup(
            item2_AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item2_AddLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        item2_AddLayout.setVerticalGroup(
            item2_AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, item2_AddLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Cont2Layout = new javax.swing.GroupLayout(Cont2);
        Cont2.setLayout(Cont2Layout);
        Cont2Layout.setHorizontalGroup(
            Cont2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cont2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Cont2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(item2_Add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Cont2Layout.createSequentialGroup()
                        .addGroup(Cont2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(item2_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Item2_Price)
                            .addComponent(Item2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(Cont2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Cont2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        Cont2Layout.setVerticalGroup(
            Cont2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Cont2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Item2)
                .addGap(18, 18, 18)
                .addComponent(Item2_Price)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(item2_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(item2_Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
            .addGroup(Cont2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Cont2Layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(96, Short.MAX_VALUE)))
        );

        Next.setBackground(new java.awt.Color(51, 0, 204));
        Next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NextMouseClicked(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NEXT");

        javax.swing.GroupLayout NextLayout = new javax.swing.GroupLayout(Next);
        Next.setLayout(NextLayout);
        NextLayout.setHorizontalGroup(
            NextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NextLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NextLayout.setVerticalGroup(
            NextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NextLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Previous.setBackground(new java.awt.Color(51, 0, 204));
        Previous.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Previous.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PreviousMouseClicked(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PREVIOUS");

        javax.swing.GroupLayout PreviousLayout = new javax.swing.GroupLayout(Previous);
        Previous.setLayout(PreviousLayout);
        PreviousLayout.setHorizontalGroup(
            PreviousLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PreviousLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel2)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        PreviousLayout.setVerticalGroup(
            PreviousLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PreviousLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(Nav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(Previous, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Next, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Image1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Image2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cont1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cont2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Cont1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Image1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Image2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cont2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Next, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Previous, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked

        try{
            conn con = new conn();
            Statement s = con.c.createStatement();
            String query = "delete from cur_user";
            String query2 = "delete from user_cart";
            s.executeUpdate(query);
            s.executeUpdate(query2);
            
        }catch (Exception e){
            e.getStackTrace();
        }
        
        JOptionPane.showMessageDialog(this, "Sucessfully Logout!", "Logout", JOptionPane.PLAIN_MESSAGE);
        
        LoginPage l = new LoginPage();
        this.setVisible(false);
        l.setVisible(true);
    }//GEN-LAST:event_LogoutMouseClicked

    private void SettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMouseClicked
        AccSettings s = new AccSettings();
        this.setVisible(false);
        s.setVisible(true);
    }//GEN-LAST:event_SettingsMouseClicked

    private void FeedbacksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FeedbacksMouseClicked
        Feedback f = new Feedback();
        this.setVisible(false);
        f.setVisible(true);
    }//GEN-LAST:event_FeedbacksMouseClicked

    private void NextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextMouseClicked
        this.item1_Quantity.setSelectedIndex(0);
        this.item2_Quantity.setSelectedIndex(0);
        
        String item1_Name = "";
        String item1_Price = "";
        String item2_Name = "";
        String item2_Price = "";
        
         try{
            conn con = new conn();
            String query = "select * from items where item_id = ? OR item_id = ?";
            String count = "select * from items";
            
            Statement stmt = con.c.createStatement();
            PreparedStatement ps = con.c.prepareStatement(query);

            ResultSet rs = stmt.executeQuery(count);
            int size = 0;
            while(rs.next()){
                size++;
            }
            
            if(j == size || i == (size-1)){
                i = 1;
                j = 2;
                
                ps.setString(1, i.toString());
                ps.setString(2, j.toString());
            
                rs = ps.executeQuery();
            }
            else{
                i += 2;
                j += 2;
                ps.setString(1, i.toString());
                ps.setString(2, j.toString());
            
                rs = ps.executeQuery();
            }
                //Setting cont 1
                rs.next();
                item1_Name = rs.getString("item_name");
                item1_Price = rs.getString("item_price");

                //Setting cont 2
                rs.next();
                item2_Name = rs.getString("item_name");
                item2_Price = rs.getString("item_price");
                
                this.Item1.setText(item1_Name);
                this.Item1_Price.setText("Price: Rs." + item1_Price + "/kg");
                this.Item2.setText(item2_Name);
                this.Item2_Price.setText("Price: Rs." + item2_Price + "/kg");
                this.Image1.setIcon(new javax.swing.ImageIcon("C:\\Users\\nano\\Documents\\NetBeansProjects\\Kaimono\\src\\main\\java\\kaimone\\Vegitables\\" + i.toString() + ".jpg"));
                this.Image2.setIcon(new javax.swing.ImageIcon("C:\\Users\\nano\\Documents\\NetBeansProjects\\Kaimono\\src\\main\\java\\kaimone\\Vegitables\\" + j.toString() + ".jpg"));
            
        }catch (Exception e){
            e.getStackTrace();
        }
    }//GEN-LAST:event_NextMouseClicked

    private void PreviousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PreviousMouseClicked
        this.item1_Quantity.setSelectedIndex(0);
        this.item2_Quantity.setSelectedIndex(0);
        
        String item1_Name = "";
        String item1_Price = "";
        String item2_Name = "";
        String item2_Price = "";
        
         try{
            conn con = new conn();
            String query = "select * from items where item_id = ? OR item_id = ?";
            String count = "select * from items";
            
            Statement stmt = con.c.createStatement();
            PreparedStatement ps = con.c.prepareStatement(query);

            ResultSet rs = stmt.executeQuery(count);
            int size = 0;
            while(rs.next()){
                size++;
            }
            
            if(i == 1){
                i = size-1;
                j = size;
                
                ps.setString(1, i.toString());
                ps.setString(2, j.toString());
            
                rs = ps.executeQuery();
            }
            else{
                i -= 2;
                j -= 2;
                ps.setString(1, i.toString());
                ps.setString(2, j.toString());
            
                rs = ps.executeQuery();
            }
                //Setting cont 1
                rs.next();
                item1_Name = rs.getString("item_name");
                item1_Price = rs.getString("item_price");

                //Setting cont 2
                rs.next();
                item2_Name = rs.getString("item_name");
                item2_Price = rs.getString("item_price");
                
                this.Item1.setText(item1_Name);
                this.Item1_Price.setText("Price: Rs." + item1_Price + "/kg");
                this.Item2.setText(item2_Name);
                this.Item2_Price.setText("Price: Rs." + item2_Price + "/kg");
                this.Image1.setIcon(new javax.swing.ImageIcon("C:\\Users\\nano\\Documents\\NetBeansProjects\\Kaimono\\src\\main\\java\\kaimone\\Vegitables\\" + i.toString() + ".jpg"));
                this.Image2.setIcon(new javax.swing.ImageIcon("C:\\Users\\nano\\Documents\\NetBeansProjects\\Kaimono\\src\\main\\java\\kaimone\\Vegitables\\" + j.toString() + ".jpg"));
            
        }catch (Exception e){
            e.getStackTrace();
        }
    }//GEN-LAST:event_PreviousMouseClicked

    private void MyCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyCartMouseClicked
        MyCart mc = new MyCart();
        this.setVisible(false);
        mc.setVisible(true);
    }//GEN-LAST:event_MyCartMouseClicked

    private void item1_AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item1_AddMouseClicked
        String quantity = "";
        if(this.item1_Quantity.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Please select Quantity!","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            switch(this.item1_Quantity.getSelectedIndex()){
                case 1: quantity = "1"; break;
                case 2: quantity = "2.5"; break;
                case 3: quantity = "5"; break;
                case 4: quantity = "10"; break;
            }
        
        
            //used as key
            String item_name = this.Item1.getText();

            //Inserting values
             try{
                conn con = new conn();
                Statement stmt = con.c.createStatement();
                String query = "insert into user_cart (item_id,item_name,item_price) "
                        + "select item_id,item_name,item_price from items "
                        + "where item_name = ?";
                PreparedStatement ps = con.c.prepareStatement(query);

                ps.setString(1, item_name);

                ps.executeUpdate();

                String query2 = "update user_cart set item_quantity = ? where item_name = ?";
                ps = con.c.prepareStatement(query2);
                ps.setString(1, quantity);
                ps.setString(2, item_name);

                ps.executeUpdate();

                String query3 = "update user_cart set item_netprice = item_quantity * item_price";
                stmt.executeUpdate(query3);

                JOptionPane.showMessageDialog(this, quantity + "Kg " + item_name + " added to cart");

            }catch (Exception e){
                e.getStackTrace();
            }
        }
    }//GEN-LAST:event_item1_AddMouseClicked

    private void item2_AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item2_AddMouseClicked
        String quantity = "";
        if(this.item2_Quantity.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Please select Quantity!","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            switch(this.item2_Quantity.getSelectedIndex()){
                case 1: quantity = "1"; break;
                case 2: quantity = "2.5"; break;
                case 3: quantity = "5"; break;
                case 4: quantity = "10"; break;
            }
        
        
            //used as key
            String item_name = this.Item2.getText();

            //Inserting values
             try{
                conn con = new conn();
                Statement stmt = con.c.createStatement();
                String query = "insert into user_cart (item_id,item_name,item_price) "
                        + "select item_id,item_name,item_price from items "
                        + "where item_name = ?";
                PreparedStatement ps = con.c.prepareStatement(query);

                ps.setString(1, item_name);

                ps.executeUpdate();

                String query2 = "update user_cart set item_quantity = ? where item_name = ?";
                ps = con.c.prepareStatement(query2);
                ps.setString(1, quantity);
                ps.setString(2, item_name);

                ps.executeUpdate();

                String query3 = "update user_cart set item_netprice = item_quantity * item_price";
                stmt.executeUpdate(query3);

                JOptionPane.showMessageDialog(this, quantity + "Kg " + item_name + " added to cart");

            }catch (Exception e){
                e.getStackTrace();
            }
        }
    }//GEN-LAST:event_item2_AddMouseClicked

    private void CheckoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckoutMouseClicked
        Checkout c = new Checkout();
        this.setVisible(false);
        c.setVisible(true);
    }//GEN-LAST:event_CheckoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new MainMenu().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Checkout;
    private javax.swing.JPanel Cont1;
    private javax.swing.JPanel Cont2;
    private javax.swing.JPanel Feedbacks;
    private javax.swing.JLabel Image1;
    private javax.swing.JLabel Image2;
    private javax.swing.JLabel Item1;
    private javax.swing.JLabel Item1_Price;
    private javax.swing.JLabel Item2;
    private javax.swing.JLabel Item2_Price;
    private javax.swing.JLabel KaimonoH;
    private javax.swing.JLabel Logout;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel MyCart;
    private javax.swing.JPanel Nav;
    private javax.swing.JPanel Next;
    private javax.swing.JPanel Previous;
    private javax.swing.JPanel Settings;
    private javax.swing.JLabel cartlable;
    private javax.swing.JPanel item1_Add;
    private javax.swing.JComboBox<String> item1_Quantity;
    private javax.swing.JPanel item2_Add;
    private javax.swing.JComboBox<String> item2_Quantity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
